source 'https://rubygems.org'

gem "sinatra"
gem 'sinatra-contrib'
gem "pry"
gem "spec"
gem "rspec"
gem "rspec-core"
gem 'guard'
gem 'guard-rspec'
gem 'rspec-mocks'
gem 'imdb'

# Specify your gem's dependencies in MovieLovers.gemspec
gemspec
