# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06f8d7f908ca2477bb25ebb1260a8874645a259091f8c3f9a11cf670d6d1b049a7de1f84c55f5fd8b20ee503a688d9de3a78e25594c9e4547a7aaafcd9c94f45

test:
  secret_key_base: 7434ecf933d9d57a041e759ed509a3f4db5efb1b3ca3e532f13fe9fc0b2f0b809cd8f545f1142c0566da2a7d0d936710c0ae9a359356babfd8b3f1fd2da59890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
